alter table sex_type add primary key (sex_type_id);
alter table teretory add primary key (teretory_id);
alter table area add primary key (area_id);
alter table region add primary key (region_id);
alter table teretory_type add primary key (teretory_type_id);
alter table reg_type add primary key (reg_type_id);
alter table class_profile add primary key (class_profile_id);
alter table subject add primary key (subject_id);
alter table all_languages add primary key (language_id);
alter table education_place add primary key (education_place_id);
alter table education_place_types add primary key(education_place_type_id);
alter table education_place_parent add primary key(education_place_parent_id);
alter table student add primary key (out_id);
alter table test add primary key (test_id);

alter table teretory add foreign key (area_id) references area(area_id);
alter table area add foreign key (region_id) references region(region_id);
alter table teretory add foreign key (teretory_type_id) references teretory_type(teretory_type_id);
alter table education_place add foreign key (teretory_id) references teretory(teretory_id);
alter table education_place add foreign key (education_place_type_id) references education_place_types(education_place_type_id);
alter table education_place add foreign key (education_place_parent_id) references education_place_parent(education_place_parent_id);
alter table students_tests add foreign key (out_id) references student(out_id);
alter table students_tests add foreign key (test_id) references test(test_id);
alter table student add foreign key (education_place_id) references education_place(education_place_id);
alter table student add foreign key (language_id) references all_languages(language_id);
alter table student add foreign key (class_profile_id) references class_profile(class_profile_id);
alter table student add foreign key (reg_type_id) references reg_type(reg_type_id);
alter table student add foreign key (teretory_id) references teretory(teretory_id);
alter table student add foreign key (sex_type_id) references sex_type(sex_type_id);
alter table test add foreign key (subject_id) references subject(subject_id);
alter table test add foreign key (language_id) references all_languages(language_id);
alter table test add foreign key (education_place_id) references education_place(education_place_id);
